In [1]:
#numpy >> numerical python 
#2005 by Travis Oliphant

In [3]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [6]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2]

In [7]:
type(lis)

list

In [8]:
lis

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]

In [9]:
#Numpy stores the data in an array
#An array is a container used to store the data of same data type

In [10]:
#why numpy
#Computation is fast>> due to array>>>continous memory location
#mathematical computation

In [11]:
l = [1,2,3,4,5]
arr = np.array(l)

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
l = [1,2,3,4,5.5]
arr = np.array(l)

In [14]:
arr

array([1. , 2. , 3. , 4. , 5.5])

In [15]:
l = [1,2,3,"Ajay"]
arr = np.array(l)

In [16]:
arr


array(['1', '2', '3', 'Ajay'], dtype='<U21')

In [17]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim #means this is one dimensios array

1

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1.ndim

2

In [23]:
matriX = np.matrix([1,2,3,4,5,6]) ##matrix is a specialised array, 2 dimensional

In [24]:
type(matriX)

numpy.matrix

In [25]:
#more way to convert array
l = [1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

In [26]:
matriX

matrix([[1, 2, 3, 4, 5, 6]])

In [27]:
np.array(matriX)

array([[1, 2, 3, 4, 5, 6]])

In [28]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [29]:
np.asanyarray(matriX)

matrix([[1, 2, 3, 4, 5, 6]])

In [8]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [9]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
list = [3,4,5,6]
arr2 = np.array(list)

In [11]:
arr2

array([3, 4, 5, 6])

In [12]:
arr2[0]

3

In [13]:
arr2[0]=4

In [14]:
arr2

array([4, 4, 5, 6])

In [15]:
a = arr2

In [16]:
arr2[0] = 100

In [17]:
a #change in array also lead to change in a >> shalow copy

array([100,   4,   5,   6])

In [18]:
arr2

array([100,   4,   5,   6])

In [20]:
a = arr2.copy()

In [21]:
a

array([100,   4,   5,   6])

In [22]:
arr2

array([100,   4,   5,   6])

In [23]:
arr2[0] = 2000

In [24]:
arr2

array([2000,    4,    5,    6])

In [25]:
a

array([100,   4,   5,   6])

In [27]:
#multiple to generate array
arr1 = np.fromfunction(lambda i,j:i==j,(3,3))#construct to a function over each cordinate 

In [28]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
arr1.ndim

2

In [30]:
arr1.shape

(3, 3)

In [31]:
arr1.size

9

In [33]:
arr2 = np.fromfunction(lambda i,j:i*j,(3,3))

In [34]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [43]:
iterable = [i for i in range(5)]

In [44]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [46]:
np.fromstring('22,23,24', sep = ",")

array([22., 23., 24.])

In [47]:
#for string character you have  to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [48]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])