In [3]:
import numpy as np

In [7]:
a = np.zeros(6)

In [8]:
a

array([0., 0., 0., 0., 0., 0.])

In [9]:
a.ndim

1

In [4]:
b=np.zeros((3,4))

In [5]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b.ndim

2

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.array([[2,2,2,2],[2,2,2]])

/tmp/ipykernel_77/3898704553.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[2,2,2,2],[2,2,2]])


array([list([2, 2, 2, 2]), list([2, 2, 2])], dtype=object)

In [13]:
np.zeros(1)

array([0.])

In [15]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr = np.zeros((1,3,4))

In [17]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
arr.ndim

3

In [19]:
arr = np.zeros((1,1,3,4))

In [20]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [21]:
arr.ndim

4

In [22]:
arr = np.zeros((1,1,1,3,4))

In [23]:
arr.ndim

5

In [25]:
arr = np.zeros((3,4))

In [26]:
arr.ndim

2

In [27]:
arr.shape

(3, 4)

In [31]:
a = arr + 5

In [29]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr-1

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [32]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [33]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [34]:
a*5

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

In [35]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
np.empty((3,4))

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

In [6]:
#optional >> Random module
import random
random.choice((1,2,3,4))

2

In [11]:
random.choice('ajay')

'y'

In [16]:
random.randrange(1,10)

3

In [18]:
random.random()

0.669887060159619

In [19]:
list = [1,2,3,4]
random.shuffle(list)

In [20]:
list

[4, 1, 2, 3]

In [24]:
random.uniform(7,14)

13.284112328057219

In [4]:
#random numbers related concepts in numpy
import numpy as np
np.array([])

array([], dtype=float64)

In [27]:
np.random.random_sample()

0.038317069429429584

In [28]:
np.random.random_sample((5,)) #can generate 5 array element 

array([0.07734127, 0.03836701, 0.70614943, 0.54819371, 0.44332968])

In [29]:
np.random.rand(1) #can generate only one value

array([0.45080202])

In [31]:
np.random.rand(2,3) #genrete random array of 2 row and 3 cols

array([[0.20187256, 0.22316604, 0.9030984 ],
       [0.91642118, 0.38711456, 0.47262977]])

In [8]:
arr = np.random.randint(1, 5, size= (3, 4))

In [9]:
arr

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [10]:
#reshaping the array
arr

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [14]:
arr1 = arr.reshape(2,6)

In [15]:
arr1

array([[4, 1, 4, 1, 1, 1],
       [1, 3, 1, 3, 4, 1]])

In [16]:
arr1.size

12

In [1]:
#array size will not change, always resape parameter should be multiplication of original array size

In [11]:
arr

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [12]:
arr.size

12

In [13]:
arr.reshape(12,1)

array([[4],
       [1],
       [1],
       [4],
       [2],
       [2],
       [4],
       [4],
       [1],
       [3],
       [1],
       [4]])

In [14]:
arr.reshape(1,12)

array([[4, 1, 1, 4, 2, 2, 4, 4, 1, 3, 1, 4]])

In [15]:
arr.reshape(2,6)

array([[4, 1, 1, 4, 2, 2],
       [4, 4, 1, 3, 1, 4]])

In [16]:
arr.reshape(6,2)

array([[4, 1],
       [1, 4],
       [2, 2],
       [4, 4],
       [1, 3],
       [1, 4]])

In [17]:
arr.reshape(3,4)

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [18]:
arr.reshape(4,3)

array([[4, 1, 1],
       [4, 2, 2],
       [4, 4, 1],
       [3, 1, 4]])

In [19]:
arr.reshape(2,6)

array([[4, 1, 1, 4, 2, 2],
       [4, 4, 1, 3, 1, 4]])

In [21]:
arr.reshape(4,-1)

array([[4, 1, 1],
       [4, 2, 2],
       [4, 4, 1],
       [3, 1, 4]])

In [22]:
arr.reshape(-1,4)

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [24]:
arr1 = arr.reshape(2,-1)

In [25]:
arr1

array([[4, 1, 1, 4, 2, 2],
       [4, 4, 1, 3, 1, 4]])

In [26]:
arr1.size

12

In [27]:
arr.reshape(12,1).base #to see the original array

array([[4, 1, 1, 4],
       [2, 2, 4, 4],
       [1, 3, 1, 4]])

In [28]:
arr.reshape(2,2,3)

array([[[4, 1, 1],
        [4, 2, 2]],

       [[4, 4, 1],
        [3, 1, 4]]])

In [29]:
arr.reshape(1,3,4)

array([[[4, 1, 1, 4],
        [2, 2, 4, 4],
        [1, 3, 1, 4]]])

In [32]:
arr.reshape(1,2,2,3)

array([[[[4, 1, 1],
         [4, 2, 2]],

        [[4, 4, 1],
         [3, 1, 4]]]])

In [33]:
arr.reshape(1,2,2,3).ndim


4

In [34]:
arr.reshape(4,3,1)

array([[[4],
        [1],
        [1]],

       [[4],
        [2],
        [2]],

       [[4],
        [4],
        [1]],

       [[3],
        [1],
        [4]]])

In [5]:
#conditions on array
import numpy as np
arr1 = np.random.randint(1,10,(5,6))

In [36]:
arr1

array([[1, 2, 5, 6, 3, 6],
       [3, 5, 7, 2, 8, 8],
       [1, 1, 7, 4, 8, 3],
       [7, 4, 8, 3, 1, 9],
       [7, 1, 1, 2, 4, 2]])

In [37]:
arr1.shape

(5, 6)

In [38]:
arr1.size

30

In [39]:
arr1.ndim

2

In [40]:
arr1 > 3

array([[False, False,  True,  True, False,  True],
       [False,  True,  True, False,  True,  True],
       [False, False,  True,  True,  True, False],
       [ True,  True,  True, False, False,  True],
       [ True, False, False, False,  True, False]])

In [41]:
arr1 < 3

array([[ True,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False, False,  True, False],
       [False,  True,  True,  True, False,  True]])

In [42]:
arr1[arr1<3]

array([1, 2, 2, 1, 1, 1, 1, 1, 2, 2])

In [43]:
arr1[arr1>3]

array([5, 6, 6, 5, 7, 8, 8, 7, 4, 8, 7, 4, 8, 9, 7, 4])

In [44]:
arr1

array([[1, 2, 5, 6, 3, 6],
       [3, 5, 7, 2, 8, 8],
       [1, 1, 7, 4, 8, 3],
       [7, 4, 8, 3, 1, 9],
       [7, 1, 1, 2, 4, 2]])

In [45]:
arr1[0]

array([1, 2, 5, 6, 3, 6])

In [6]:
arr1[0][0]

6

In [7]:
arr1[0][1]

2

In [9]:
arr1[0][4]

2

In [10]:
arr1[1]

array([6, 6, 3, 6, 1, 9])

In [11]:
arr1

array([[6, 2, 7, 1, 2, 7],
       [6, 6, 3, 6, 1, 9],
       [5, 1, 9, 4, 3, 9],
       [5, 7, 4, 1, 1, 8],
       [1, 4, 4, 6, 1, 2]])

In [12]:
arr1[2]

array([5, 1, 9, 4, 3, 9])

In [13]:
arr1[3]

array([5, 7, 4, 1, 1, 8])

In [14]:
arr1[0:3]

array([[6, 2, 7, 1, 2, 7],
       [6, 6, 3, 6, 1, 9],
       [5, 1, 9, 4, 3, 9]])

In [15]:
arr1[0:4]

array([[6, 2, 7, 1, 2, 7],
       [6, 6, 3, 6, 1, 9],
       [5, 1, 9, 4, 3, 9],
       [5, 7, 4, 1, 1, 8]])

In [17]:
arr1[0:3,[0,1]]

array([[6, 2],
       [6, 6],
       [5, 1]])

In [18]:
arr1[2:4,[4]]

array([[3],
       [1]])

In [19]:
arr1

array([[6, 2, 7, 1, 2, 7],
       [6, 6, 3, 6, 1, 9],
       [5, 1, 9, 4, 3, 9],
       [5, 7, 4, 1, 1, 8],
       [1, 4, 4, 6, 1, 2]])

In [20]:
arr1[0:4,1:3]

array([[2, 7],
       [6, 3],
       [1, 9],
       [7, 4]])

In [21]:
arr1[2:5]

array([[5, 1, 9, 4, 3, 9],
       [5, 7, 4, 1, 1, 8],
       [1, 4, 4, 6, 1, 2]])

In [22]:
#mathematical operation on two arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [23]:
arr1


array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [24]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [25]:
arr1 + arr2

array([[3, 3, 4],
       [3, 4, 3],
       [3, 3, 3]])

In [26]:
arr1 - arr2

array([[ 1,  1,  0],
       [ 1,  0,  1],
       [-1, -1, -1]])

In [27]:
arr1 * arr2

array([[2, 2, 4],
       [2, 4, 2],
       [2, 2, 2]])

In [28]:
arr1 * arr2


array([[2, 2, 4],
       [2, 4, 2],
       [2, 2, 2]])

In [29]:
arr1 , arr2


(array([[2, 2, 2],
        [2, 2, 2],
        [1, 1, 1]]),
 array([[1, 1, 2],
        [1, 2, 1],
        [2, 2, 2]]))

In [30]:
arr1/arr2

array([[2. , 2. , 1. ],
       [2. , 1. , 2. ],
       [0.5, 0.5, 0.5]])

In [31]:
arr1/0

/tmp/ipykernel_525/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [32]:
arr1 @ arr2

array([[ 8, 10, 10],
       [ 8, 10, 10],
       [ 4,  5,  5]])

In [33]:
np.dot(arr1,arr2)

array([[ 8, 10, 10],
       [ 8, 10, 10],
       [ 4,  5,  5]])

In [34]:
ar = np.zeros((5,6))

In [35]:
ar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
ar+4

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

In [37]:
ar-3

array([[-3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3.]])

In [40]:
a2 = a +ar

In [41]:
a2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.array